name: Sync upstream

on:
  schedule:
    # 每天凌晨 0 点（UTC 时间）运行
    # 你可以根据需要调整 cron 表达式
    - cron: '0 0 * * *'
  # 也可以添加 workflow_dispatch 允许手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # 获取完整的历史记录，以便合并
        fetch-depth: 0

    # === 新增步骤：配置 Git 身份 ===
    - name: Configure Git identity
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    # ===============================

    - name: Add upstream remote
      run: |
        # 请确认这里的 upstream 仓库地址是正确的
        git remote add upstream https://github.com/ultralytics/ultralytics.git

    - name: Fetch upstream
      run: |
        git fetch upstream

    - name: Merge upstream/main
      run: |
        # 假设你想同步 upstream 的 main 分支到你 fork 的 main 分支
        # 如果 upstream 的主分支是 master，或者你想同步其他分支，请修改这里的 'main'
        # 添加 --no-edit 避免在合并时尝试打开编辑器（尽管 Actions 环境下不会）
        git merge upstream/main -m "Merge upstream changes"

    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
