
The updated workflow file Modify the Workflow File
In the `.github/workflows/main should look like this:

```yaml
name: Sync upstream.yml` file, ensure you are using the correct token with the

on:
  schedule:
    - cron: '0 0 necessary permissions. Replace `GITHUB_TOKEN` * * *'
  workflow_dispatch:

permissions:
  with your PAT if needed:

```yaml
- name: Push changes
contents: write
  workflows: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth:  run: git push https://<your-token>@github.com/y 0

    - name: Configure Git identity
      run: |
        git config user.name "github-actions[xliang/ultralytics.git main
env:
 GITHUB_TOKEN:bot]"
        git config user.email "github-actions[ ${{ secrets.GITHUB_TOKEN }}
